import { KaitaiStream } from "./KaitaiStream.js";

/**
 * Common base class for all structures generated by Kaitai Struct.
 * Stores stream object that this object was parsed from in {@link #_io}.
 */
export abstract class KaitaiStruct {
  protected _io!: KaitaiStream;

  protected constructor(io?: KaitaiStream) {
    // Prevent enumeration of protected properties.
    setEnumerable(this, "_io", false);

    if (io !== undefined)
      this._io = io;
  }

  public abstract _fetchInstances(): void;
}

export namespace KaitaiStruct {
  export abstract class ReadOnly extends KaitaiStruct {
    public abstract _read(): void;
  }

  export abstract class ReadWrite extends ReadOnly {
    /**
     * Indicates whether the object has been externally modified since the
     * last known consistent state, meaning that the consistency of the
     * object is unknown because it hasn't been checked.
     *
     * Declared as private to prevent polluting the class members.
     */
    protected _dirty = true;

    protected constructor(io?: KaitaiStream) {
      super(io);

      // Prevent enumeration of protected properties.
      setEnumerable(this, "_dirty", false);

      return new Proxy(this, {
        set: (target, prop, value, receiver) => {
          if (typeof prop === "string") {
            // Mark the object as dirty when a public attribute is changed.
            if (!target._dirty && isPublicAttribute(prop))
              Reflect.set(target, "_dirty", true);
          }
          return Reflect.set(target, prop, value, receiver);
        }
      });
    }

    public abstract _check(): void;

    public _write_Seq(io?: KaitaiStream): void {
      if (io !== undefined)
        this._io = io;
      if (this._dirty)
        throw new ConsistencyNotCheckedError();
    }

    public _write(io?: KaitaiStream): void {
      this._write_Seq(io);
      this._fetchInstances();
    }
  }

  /**
   * Exception thrown by {@link KaitaiStruct.ReadWrite#_check()} when the
   * consistency check of the object is not passed.
   */
  export class ConsistencyError extends Error {
    public id: string;
    public expected: any;
    public actual: any;

    /**
     * @param id Identifier of the field that failed the consistency check.
     * @param expected The expected value.
     * @param actual The actual value.
     */
    public constructor(id: string, expected: any, actual: any) {
      const expectedStr = KaitaiStream.stringifyValue(expected);
      const actualStr = KaitaiStream.stringifyValue(actual);
      super(`Check failed: ${id}, expected: ${expectedStr}, actual: ${actualStr}`);
      this.id = id;
      this.expected = expected;
      this.actual = actual;
    }
  }

  /**
   * Exception thrown by {@link KaitaiStruct.ReadWrite#_write()} when attempting
   * to write an object whose consistency hasn't been checked
   * ({@link KaitaiStruct.ReadWrite#_check()}) since the last modification.
   */
  export class ConsistencyNotCheckedError extends Error {
    public constructor() {
      super("consistency not checked: _check() has not been called since the last modification of the object");
    }
  }
}

/**
 * Determines whether a given attribute name is considered public in Kaitai Struct.
 * Logic synchronized with python ReadWriteKaitaiStruct.__setattr__ implementation.
 *
 * @param name Name of the attribute.
 * @returns True if the attribute is public.
 */
function isPublicAttribute(name: string): boolean {
  if (!name.startsWith("_"))
    return true;
  if (name.startsWith("_unnamed"))
    return true;
  if (name.startsWith("_raw"))
    return true;
  if (name === "_root" || name === "_parent")
    return true;
  return false;
}

/**
 * Changes the enumerability of an existing property on an object.
 *
 * @param obj The object containing the property.
 * @param prop The name of the property to modify.
 * @param enumerable Whether the property should be enumerable.
 */
function setEnumerable(obj: object, prop: string, enumerable: boolean): void {
  const descriptor = Object.getOwnPropertyDescriptor(obj, prop);
  Object.defineProperty(obj, prop, { ...descriptor, enumerable });
}
