import { KaitaiStream } from "./KaitaiStream.js";

/**
 * Common base class for all structured generated by Kaitai Struct.
 * Stores stream object that this object was parsed from in {@link #_io}.
 */
export abstract class KaitaiStruct {
  protected _io!: KaitaiStream;

  constructor(io?: KaitaiStream) {
    if (io !== undefined)
      this._io = io;
  }

  public abstract _fetchInstances(): void;
}

export namespace KaitaiStruct {
  export abstract class ReadOnly extends KaitaiStruct {
    public abstract _read(): void;
  }

  export abstract class ReadWrite extends ReadOnly {
    /**
     * Indicates whether the object has been externally modified since the
     * last known consistent state, meaning that the consistency of the
     * object is unknown because it hasn't been checked.
     *
     * Declared as private to prevent polluting the class members.
     */
    #_dirty = true;

    public abstract _check(): void;

    protected _setDirty(flag: boolean): void {
      this.#_dirty = flag;
    }

    public _write_Seq(io?: KaitaiStream): void {
      if (io !== undefined)
        this._io = io;
      if (this.#_dirty)
        throw new ConsistencyNotCheckedError;
    }

    public _write(io?: KaitaiStream): void {
      this._write_Seq(io);
      this._fetchInstances();
    }
  }

  /**
   * Exception thrown by {@link KaitaiStruct.ReadWrite#_check()} when the
   * consistency check of the object is not passed.
   */
  export class ConsistencyError extends Error {
    public id: string;
    public expected: any;
    public actual: any;

    /**
     * @param id Identifier of the field that failed the consistency check.
     * @param expected The expected value.
     * @param actual The actual value.
     */
    public constructor(id: string, expected: any, actual: any) {
      const expectedStr = KaitaiStream.stringifyValue(expected);
      const actualStr = KaitaiStream.stringifyValue(actual);
      super(`Check failed: ${id}, expected: ${expectedStr}, actual: ${actualStr}`);
      this.id = id;
      this.expected = expected;
      this.actual = actual;
    }
  }

  /**
   * Exception thrown by {@link KaitaiStruct.ReadWrite#_write()} when attempting
   * to write an object whose consistency hasn't been checked
   * ({@link KaitaiStruct.ReadWrite#_check()}) since the last modification.
   */
  export class ConsistencyNotCheckedError extends Error {
    public constructor() {
      super("consistency not checked: _check() has not been called since the last modification of the object");
    }
  }
}
